Add support for optional drupal-root directory
Esrohym/grumphp-drupal-check pull request #5
Opened 2020-08-12 08:30 UTC by MPParsley

Add support for https://github.com/mglaman/drupal-check/issues/97

--drupal-root Path to Drupal root. Fallback option if drupal-check could not identify Drupal root from the provided path(s).

2020-08-12 08:34 UTC, MPParsley commented on src/DrupalCheck.php
> +    $arguments->addOptionalArgument('--drupal-root=%s', $options['drupal_root']);
```suggestion
    $arguments->add('--no-progress');
    $arguments->addOptionalArgument('--drupal-root=%s', $options['drupal_root']);
```

2020-08-12 08:35 UTC, MPParsley commented on src/DrupalCheck.php
> +    return $resolver;
Fix indentation:

```suggestion
      $resolver = new OptionsResolver();
      $resolver->setDefaults([
        'drupal_root' => null,
      ]);

      $resolver->addAllowedTypes('drupal_root', ['string']);

      return $resolver;
```

2020-08-12 08:35 UTC, MPParsley commented on src/DrupalCheck.php
> +
```suggestion
```

2020-08-12 08:36 UTC, MPParsley commented on src/DrupalCheck.php
> +    return $context instanceof GitPreCommitContext || $context instanceof RunContext;
```suggestion
      return $context instanceof GitPreCommitContext || $context instanceof RunContext;
```

2020-08-12 09:24 UTC, MPParsley commented on src/DrupalCheck.php
> +
```suggestion
```

2020-09-02 15:34 UTC, MPParsley commented
Any chance this could be merged?

I need this feature in my projects and I'd prefer not to use a fork but to contribute here.

2020-09-02 15:59 UTC, mistermoper requested changes

2020-09-02 15:59 UTC, mistermoper commented on src/DrupalCheck.php
> +      $resolver->addAllowedTypes('drupal_root', ['string']);
This line fails when you don't have drupal_root set up in configuration.

```suggestion
      $resolver->addAllowedTypes('drupal_root', ['string', 'null']);
```

2020-09-02 16:10 UTC, mistermoper commented
Sorry, I couldn't see this until now. It works fine, I've tested it and the drupal_root option is correctly setup. Thanks!
It just need one small change , already requested, and we would merge it.

2020-09-02 16:40 UTC, MPParsley commented
Great, thanks!

2020-09-02 18:58 UTC, mistermoper approved these changes

2020-09-02 18:58 UTC, merged

2020-09-02 19:06 UTC, mistermoper commented
Done @MPParsley , thanks! I suggest you to use the library from  https://packagist.org/packages/metadrop/grumphp-drupal-check instead. We don't plan to maintain this project under this namespace anymore.